### ISSUE TITLE
build for mac

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1011]
It would be nice to build it for mac so that I can use it as my primary email client. and find more bugs :-)

Is there anything special to do? Or, how to build and run it?

**Comment by ivan-ushakov** [comment]
@tomholub 
Do you mean build the same app as macOS app? If yes, then it is possible only with SwiftUI and [Catalyst](https://developer.apple.com/mac-catalyst/) technology.

**Comment by tomholub** [comment]
Ah. Is SwiftUI the only option - it would not run with Texture/ADK?

**Comment by ivan-ushakov** [comment]
> Ah. Is SwiftUI the only option - it would not run with Texture/ADK?

No, because Texture requires UIKit

**Comment by tomholub** [comment]
Here they seem to be running Texture on a mac just fine, with some bugs to work around:

https://github.com/TextureGroup/Texture/issues/1549#issuecomment-615261308

does that look feasible?

**Comment by tomholub** [comment]
Seems to build/run and function on my mac:

<img width="1501" alt="image" src="https://user-images.githubusercontent.com/6306961/143139108-35550613-7f3e-422b-a551-8680e8f7ce45.png">

**Comment by ivan-ushakov** [comment]
Great! I was thinking that if Texture is using UIKit there is no way to use it with Catalyst. Also I haven't found any signs about Catalyst support in official documentation.

Maybe we need to have separate schema for macOS build?

**Comment by tomholub** [comment]
Maybe. I'll leave that for a bit later, I've encountered some bugs when handling pass phrase.

(worked well when first set up with pass phrase in memory, but after it forgot it, kept asking for pass phrase repeatedly)

Interestingly, it's the same issue that a customer has encountered on their iOS iphone. I'll leave it for a bit later, see if they can still reproduce it on 0.5.0 iphone build, and if yes, potentially debug it on the mac app.

**Comment by sosnovsky** [comment]
I checked the latest build on M1 Macbook with macOS 13.4 and it works great - no issues with passphrase input, everything runs smoothly.

**Comment by brennanerbz** [comment]
How did you get around ```Use of undeclared identifier 'CAEAGLLayer'```?

**Comment by sosnovsky** [comment]
> How did you get around `Use of undeclared identifier 'CAEAGLLayer'`?

I didn't get such error, on which Xcode and macOS version do you try to build app? Also do you use mac with M chip?
